---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/teeterbot/fallen_over"
  gz_topic_name: "/model/teeterbot/fallen_over"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: GZ_TO_ROS
- ros_topic_name: "/teeterbot/left_speed"
  gz_topic_name: "/model/teeterbot/left_speed"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/teeterbot/right_speed"
  gz_topic_name: "/model/teeterbot/right_speed"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "/teeterbot/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "/teeterbot/left_speed_cmd"
  gz_topic_name: "/model/teeterbot/left_speed_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/teeterbot/right_speed_cmd"
  gz_topic_name: "/model/teeterbot/right_speed_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/teeterbot/left_torque_cmd"
  gz_topic_name: "/model/teeterbot/left_torque_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/teeterbot/right_torque_cmd"
  gz_topic_name: "/model/teeterbot/right_torque_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ