<?xml version="1.0"?>
<package format="3">
  <name>teeterbot_gazebo</name>
  <version>0.0.0</version>
  <description>
    Gazebo plugins for teeterbot
  </description>
  <maintainer email="mradov@gmail.com">Micho Radovnikovich</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>teeterbot_description</depend>
  <depend>gz_sim_vendor</depend>
  <depend>gz_plugin_vendor</depend>
  <depend>ros_gz</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
